version: '3.7'

services:
  frontend:
    build:
      context: ./contact-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend 

  backend:
    build:
      context: ./ContactApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=contactappdb;User=user;Password=password;
    networks:
      - contactapp-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: contactappdb
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    networks:
      - contactapp-network

volumes:
  db_data:

networks:
  contactapp-network: